### ISSUE TITLE
Misleading output diffing numbers

### ISSUE THREAD

**Issue by technomancy** [brentonashworth/lein-difftest#2]
```
expected: (= 2 21)
  actual:
    2
 - 1
```

This makes you think you expected 2 and got 1, whereas the numbers are actually 2 and 21. Should probably fall back to normal clojure.test behaviour for numbers.

**Comment by brentonashworth** [comment]
I have updated 1.3.1-SNAPSHOT to not diff small numbers. For large numbers the diffs can still be very useful.

```
expected: (= 1676543212345667876543 1676543212341667876543)
  actual:
   167654321234
 - 1
 + 5
   667876543
```

Numbers will only be diffed when both of the numbers are >= 10000.

The idea is that it is easy to eye the differences in small numbers but once you get past 4 digits it might be easier to have the diff.

I don't like the idea that 4 is completely arbitrary. What do you think of this solution?

**Comment by technomancy** [comment]
Hmm... I've never come across that situation; normally when I come across the wrong number it doesn't share any digits with the expected result except by accident.

**Comment by brentonashworth** [comment]
Okay. The questionable usefulness of this does not justify the use of a number other than 0, 1 or Infinity. It's out. I have made this change and bumped the version to 1.3.1 which is now in Clojars. Thanks for bringing this up.

**Comment by technomancy** [comment]
Sounds good; thanks a bunch!
