### ISSUE TITLE
Implicit dependency on clojure-contrib

### ISSUE THREAD

**Issue by pjstadig** [brentonashworth/lein-difftest#3]
Leiningen no longer generates new projects with a dependency on clojure-contrib.

If you create a new project with `lein new foo` and add difftest as a dependency, it will fail because cannot find clojure-contrib.

lein-diff test should add an explicit dependency on clojure-contrib.

**Comment by brentonashworth** [comment]
I have added this and pushed to Clojars as version1.3.3.

**Comment by pjstadig** [comment]
Awesome, thanks!
