### ISSUE TITLE
Bad release to clojars?

### ISSUE THREAD

**Issue by paraseba** [brentonashworth/lein-difftest#6]
The version 1.3.5 in clojars.org is incompatible with clojure 1.3.0, because _color_ is defined without the dynamic flag. Can we have a new release with this fix which is already present in the code?
Thanks a lot!

**Comment by technomancy** [comment]
Sure; just pushed out 1.3.6 with the fix.

**Comment by paraseba** [comment]
6 minutes from report to release... awesome! thank you

**Comment by brentonashworth** [comment]
technomancy is awesome!
