### ISSUE TITLE
Cannot find version 1.3.8

### ISSUE THREAD

**Issue by davejacobs** [brentonashworth/lein-difftest#7]
I've tried using difftest 1.3.7 with Leiningen 2 (latest stable) but I get errors about vars being dynamically rebound. Trying to add 1.3.8 to my Leiningen 2 profiles file yields the following when running lein for the first time:

```
Could not find artifact difftest:difftest:pom:1.3.8 in central (http://repo1.maven.org/maven2)
Could not find artifact difftest:difftest:pom:1.3.8 in clojars (http://clojars.org/repo/)
Could not find artifact difftest:difftest:pom:1.3.8 in sonatype-oss-public (https://oss.sonatype.org/content/groups/public/)
Could not find artifact difftest:difftest:jar:1.3.8 in central (http://repo1.maven.org/maven2)
Could not find artifact difftest:difftest:jar:1.3.8 in clojars (http://clojars.org/repo/)
Could not find artifact difftest:difftest:jar:1.3.8 in sonatype-oss-public (https://oss.sonatype.org/content/groups/public/)
Exception in thread "main" java.lang.RuntimeException: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact difftest:difftest:jar:1.3.8 in central (http://repo1.maven.org/maven2)
```

Is the 1.3.8 POM not yet available? Do I need to add another repository to my sources list?

I'm using Clojure 1.3.

**Comment by technomancy** [comment]
It sounds like you're looking for difftest rather than lein-difftest?

**Comment by davejacobs** [comment]
Hmm interesting... my ~/.lein/profiles.clj looks like this:

```
{:user {:plugins {lein-difftest "1.3.8"}}}
```

(This was right after a lein 1.7 -> lein 2.0 preview upgrade. It was uncomplicated and I blew away almost all files in ~/.lein.)

**Comment by technomancy** [comment]
Oh, no you are correct; it was spun off into its own library separate from the lein plugin, and that one didn't get updated. I've just uploaded it; thanks for catching this!

**Comment by davejacobs** [comment]
No problem, thanks for the fix.
